정규화는 데이터의 스케일을 조정하여 모델 학습 시 안정성과 성능을 높이는 데 사용.

---

##  scikit-learn (sklearn) 정규화 종류와 공식

### 1. Min-Max Scaling (최소-최대 스케일링)

특성(feature) 값을 0과 1 사이의 범위로 변환합니다. 데이터의 분포는 유지되지만, 이상치(Outlier)에 민감합니다.

* **sklearn 클래스:** `sklearn.preprocessing.MinMaxScaler`
* **공식:**

    $$X_{\text{norm}} = \frac{X - X_{\text{min}}}{X_{\text{max}} - X_{\text{min}}}$$

    * $X$: 원본 데이터 포인트
    * $X_{\text{min}}$: 특성의 **최솟값**
    * $X_{\text{max}}$: 특성의 **최댓값**
    * $X_{\text{norm}}$: 정규화된 값

### 2. Standard Scaling (표준화)

데이터의 평균을 0, 표준편차를 1로 조정합니다. 정규 분포(Gaussian distribution)를 따르는 데이터에 특히 유용하며, 이상치의 영향을 덜 받습니다. 이는 정규화(Normalization)보다는 **표준화(Standardization)**라고 부르는 것이 더 정확합니다.

* **sklearn 클래스:** `sklearn.preprocessing.StandardScaler`
* **공식:**

    $$z = \frac{X - \mu}{\sigma}$$

    * $X$: 원본 데이터 포인트
    * $\mu$: 특성의 **평균** (Mean)
    * $\sigma$: 특성의 **표준 편차** (Standard Deviation)
    * $z$: 표준화된 값 (Z-score)

### 3. Robust Scaling (로버스트 스케일링)

중앙값(Median)과 사분위 범위(Interquartile Range, IQR)를 사용하여 스케일링합니다. Min-Max Scaling이나 Standard Scaling보다 **이상치에 훨씬 덜 민감**합니다.

* **sklearn 클래스:** `sklearn.preprocessing.RobustScaler`
* **공식:**

    $$X_{\text{robust}} = \frac{X - Q_2}{Q_3 - Q_1}$$

    * $X$: 원본 데이터 포인트
    * $Q_1$: 특성의 **1사분위 수** (25th percentile)
    * $Q_2$: 특성의 **중앙값** (Median, 50th percentile)
    * $Q_3$: 특성의 **3사분위 수** (75th percentile)
    * $Q_3 - Q_1$: 사분위 범위 (IQR)
    * $X_{\text{robust}}$: 로버스트 스케일링된 값

### 4. Normalizer (L2 정규화)

**데이터의 개별 행(샘플)**에 대해 적용되며, 각 샘플의 벡터 길이를 1로 만듭니다. 주로 텍스트 분석이나 군집화(Clustering)에서 유클리드 거리(Euclidean distance) 기반의 유사도를 측정할 때 유용합니다.

* **sklearn 클래스:** `sklearn.preprocessing.Normalizer`
* **공식 (L2 Norm):**

    $$X_{\text{norm}} = \frac{X}{\|X\|_2}$$

    여기서 $\|X\|_2$는 L2 노름(Euclidean norm)이며 다음과 같습니다:

    $$\|X\|_2 = \sqrt{\sum_{i=1}^{n} x_i^2}$$

    * $X$: 원본 데이터 샘플 (벡터)
    * $x_i$: 벡터 $X$의 $i$번째 원소
    * $\|X\|_2$: L2 노름 (벡터의 길이)
    * $X_{\text{norm}}$: 정규화된 벡터

---

### 📚 요약 표

| 정규화/표준화 기법 | Scikit-learn 클래스 | 사용되는 통계량 | 주요 특징 |
| :--- | :--- | :--- | :--- |
| **Min-Max Scaling** | `MinMaxScaler` | $\text{Min}, \text{Max}$ | 데이터 범위를 $[0, 1]$로 조정. 이상치에 민감. |
| **Standard Scaling** | `StandardScaler` | $\mu$ (평균), $\sigma$ (표준편차) | 평균 $0$, 표준편차 $1$로 조정. 이상치의 영향 적음. |
| **Robust Scaling** | `RobustScaler` | $Q_2$ (중앙값), $IQR$ ($Q_3 - Q_1$) | 이상치에 **매우 강함**. |
| **Normalizer (L2)** | `Normalizer` | L2 Norm ($\|X\|_2$) | 개별 샘플(행)의 벡터 길이를 $1$로 조정. |

---

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.linear_model import SGDRegressor

In [2]:
data = [[828, 920, 1234567, 1020, 1111],
            [824, 910, 2345612, 1090, 1234],
            [880, 900, 3456123, 1010, 1000],
            [870, 990, 2312123, 1001, 1122],
            [860, 980, 3223123, 1008, 1133],
            [850, 970, 2432123, 1100, 1221]]
data = np.float32(data)

df = pd.DataFrame( data )
df

0      1          2       3       4
0  828.0  920.0  1234567.0  1020.0  1111.0
1  824.0  910.0  2345612.0  1090.0  1234.0
2  880.0  900.0  3456123.0  1010.0  1000.0
3  870.0  990.0  2312123.0  1001.0  1122.0
4  860.0  980.0  3223123.0  1008.0  1133.0
5  850.0  970.0  2432123.0  1100.0  1221.0

In [3]:
x_data = df.iloc[:,:-1].values
y_data = df.iloc[:,[-1]].values

In [4]:
scaleF = MinMaxScaler()
x_dataN = scaleF.fit_transform( x_data)
x_dataN

array([[0.0714283 , 0.22222233, 0.        , 0.19191933],
       [0.        , 0.11111164, 0.50012016, 0.89899063],
       [1.        , 0.        , 1.        , 0.09090996],
       [0.8214283 , 1.        , 0.48504567, 0.        ],
       [0.6428566 , 0.8888893 , 0.8951186 , 0.07070732],
       [0.4642849 , 0.7777777 , 0.5390618 , 1.        ]], dtype=float32)

In [5]:
scaleL = MinMaxScaler()
y_dataN = scaleL.fit_transform( y_data)
y_dataN

array([[0.47435904],
       [1.0000005 ],
       [0.        ],
       [0.52136755],
       [0.56837654],
       [0.94444466]], dtype=float32)

In [ ]:
model = SGDRegressor(verbose=True, max_iter=200)
model.fit( x_dataN, y_dataN)

-- Epoch 1
Norm: 0.02, NNZs: 4, Bias: 0.025828, T: 6, Avg. loss: 0.214279
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.04, NNZs: 4, Bias: 0.043569, T: 12, Avg. loss: 0.190653
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.06, NNZs: 4, Bias: 0.058418, T: 18, Avg. loss: 0.173907
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 0.07, NNZs: 4, Bias: 0.071324, T: 24, Avg. loss: 0.160436
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 0.08, NNZs: 4, Bias: 0.082822, T: 30, Avg. loss: 0.149237
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 0.09, NNZs: 4, Bias: 0.093254, T: 36, Avg. loss: 0.139680
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 0.10, NNZs: 4, Bias: 0.102788, T: 42, Avg. loss: 0.131387
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 0.11, NNZs: 4, Bias: 0.111594, T: 48, Avg. loss: 0.124099
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 0.12, NNZs: 4, Bias: 0.119758, T: 54, Avg. loss: 0.117659
Total training time: 0.00 seconds.
-- Epoch 10

c:\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDRegressor(max_iter=200, verbose=True)

In [ ]:
#828, 920, 1234567, 1020
xN = scaleF.transform([[828, 920, 1234567, 1020]])
pred = model.predict( xN)
pred

array([0.30318136])

In [ ]:
scaleL.inverse_transform( [pred])

array([[1070.94438187]])