In [ ]:
pip install torch torchvision

In [1]:
import torch

In [2]:
torch.__version__

'2.0.1+cpu'

In [3]:
t1 = torch.tensor( [1,2,3,4,5], dtype=torch.float32)
t1

tensor([1., 2., 3., 4., 5.])

In [4]:
# 미분을 통해 수정되는 텐서노드
t2 = torch.tensor( 2.0, dtype=torch.float32, requires_grad=True)
t2

tensor(2., requires_grad=True)

In [5]:
t3 = torch.FloatTensor( [1,2,3,4,5] )

In [6]:
t4 = torch.IntTensor( [1,2,3,4,5] )

In [7]:
t4.numpy()

array([1, 2, 3, 4, 5])

In [11]:
t5 = torch.tensor( 10 ) # scalar 노드면 item()
t5.item()

10

In [12]:
## 연산
a = torch.tensor( 5 )
b = torch.tensor( [1,2,3])

In [16]:
type( a )

torch.Tensor

In [15]:
c = torch.add( a,b ) # [5,5,5] + [1,2,3]
c

tensor([6, 7, 8])

In [17]:
d = a.add( b )
d

tensor([6, 7, 8])

In [18]:
e = a+b
e

tensor([6, 7, 8])

## 인덱싱 슬라이싱

In [19]:
t = torch.tensor( [11,22,33,44,55])
t

tensor([11, 22, 33, 44, 55])

In [21]:
t[0].item()

11

In [22]:
t[-1]

tensor(55)

In [24]:
t[1:3].numpy()

array([22, 33], dtype=int64)