In [7]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('data/cars.csv', index_col='Unnamed: 0')
df

In [17]:
x = torch.FloatTensor( df[['speed']].values )
y = torch.FloatTensor( df[['dist']].values )

In [9]:
linear = Linear( 1, 1 ) # w:1x1, b:1, hx = w*x + b
print( list( linear.parameters() )  )

[Parameter containing:
tensor([[-0.0515]], requires_grad=True), Parameter containing:
tensor([-0.5950], requires_grad=True)]


In [14]:
linear( torch.FloatTensor( [[15],[20]] ) )

tensor([[-1.3680],
        [-1.6256]], grad_fn=<AddmmBackward0>)

In [15]:
linear.forward( torch.FloatTensor( [[15],[20]] ) )

tensor([[-1.3680],
        [-1.6256]], grad_fn=<AddmmBackward0>)

In [ ]:
linear = Linear( 1,1)
model = Sequential()
model.add_module( 'nn1', linear )

loss_fn = MSELoss()
optimizer = Adam( model.parameters(),  lr=0.1)
for step in range(1000):
    optimizer.zero_grad()
    hx = model(x) # linear(x) --> w*x + b
    cost = loss_fn( hx, y ) 
    cost.backward()
    optimizer.step()
    print( step, cost.item() )

In [19]:
model( torch.FloatTensor( [[15],[20]] ) )

tensor([[41.5453],
        [60.8738]], grad_fn=<AddmmBackward0>)

In [20]:
model.forward( torch.FloatTensor( [[15],[20]] ) )

tensor([[41.5453],
        [60.8738]], grad_fn=<AddmmBackward0>)