In [1]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv( 'data/test.csv',header=None)
df.columns = ['q1','q2','mid','final']
df

In [3]:
x_data = df.iloc[:, :-1].values
y_data = df.iloc[:, [-1]].values

In [4]:
x = torch.FloatTensor( x_data )
y = torch.FloatTensor( y_data )

In [5]:
model = Sequential()
model.add_module( 'nn1', Linear( 3,1 )) # w:3x1, b:1
loss_fn = MSELoss()
optimizer = Adam( model.parameters(), lr=0.1 )

In [ ]:
for epoch in range(1000):
    optimizer.zero_grad()
    hx = model(x) # hx = torch.matmul( x, w) + b
    cost = loss_fn( hx, y )
    cost.backward()
    optimizer.step()
    print( 'cost:', cost.item())

In [ ]:
list( model[0].parameters() )

In [ ]:
list( model.parameters() )

In [11]:
model[0].weight

Parameter containing:
tensor([[0.4701, 0.6253, 0.9154]], requires_grad=True)

In [13]:
# q1:90, q2:90, mid:80 예측값을 구하시요.
model.forward( torch.FloatTensor( [[90,90,80]] ) )

tensor([[172.4809]], grad_fn=<AddmmBackward0>)

### low level

In [14]:
x_data = df.iloc[:, :-1].values
y_data = df.iloc[:, [-1]].values

In [15]:
x = torch.FloatTensor( x_data )
y = torch.FloatTensor( y_data )

In [16]:
w = torch.empty( [3,1],requires_grad=True) # [특성데이터갯수, 라벨갯수]
b = torch.empty( [1],requires_grad=True)# [라벨갯수]
torch.nn.init.uniform_(w)
torch.nn.init.uniform_(b)

tensor([0.7055], requires_grad=True)

In [17]:
def cost():
    hx = torch.matmul( x,w) +b
    c = torch.mean( (hx-y)**2 )
    return c

In [ ]:
optimizer = Adam( [w,b], lr=0.01)
for epoch in range( 1000):
    c = cost()
    optimizer.zero_grad()
    c.backward()
    optimizer.step()
    print( 'cost:', c.item())

In [19]:
def hxFn( xd ):
    xd = torch.FloatTensor( xd )
    hx = torch.matmul( xd,w ) + b
    return hx.detach().numpy()

In [20]:
hxFn( [[80,90,90]] )

array([[176.7117]], dtype=float32)