In [1]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential, CrossEntropyLoss,Softmax
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv( 'data/softmax.txt',sep=' ', header=None)
df

In [3]:
x_data = df.iloc[:, 0:2]
y_data = df.iloc[:,2:]

In [4]:
x= torch.FloatTensor( x_data.values )
y= torch.FloatTensor( y_data.values )

In [10]:
s = torch.nn.Softmax()
s1 = torch.nn.Softmax(dim=1)
s2 = torch.nn.Softmax(dim=0)
rdata = torch.randn( 2,3 )
rdata

tensor([[ 0.8125, -0.2996, -0.3370],
        [ 0.8710,  0.0277,  0.1798]])

In [8]:
s( rdata )

C:\Users\NT350XCR\AppData\Local\Temp\ipykernel_10140\3874667218.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  s( rdata )


tensor([[0.8876, 0.0548, 0.0576],
        [0.4600, 0.2620, 0.2780]])

In [9]:
s1( rdata )

tensor([[0.8876, 0.0548, 0.0576],
        [0.4600, 0.2620, 0.2780]])

In [11]:
s2( rdata )

tensor([[0.4854, 0.4189, 0.3736],
        [0.5146, 0.5811, 0.6264]])

In [12]:
model = Sequential()
model.add_module( 'nn1', Linear( 2,3)) # w:2x3, b:3
model.add_module( 'soft1', Softmax( dim=1))
loss_fn = CrossEntropyLoss()
optimizer = Adam( model.parameters(), lr= 0.01 )

In [ ]:
for step in range(2000):
    optimizer.zero_grad()
    hx = model(x)  #z =matmul( x, w) + b => hx = softmax( z ) 
    cost = loss_fn( hx, y)
    cost.backward()
    optimizer.step()
    print( step, cost.item())

In [17]:
model( torch.FloatTensor( [[5,6], [2,1] ]) ) 

tensor([[4.6788e-09, 9.9923e-01, 7.6676e-04],
        [1.1532e-05, 9.6035e-07, 9.9999e-01]], grad_fn=<SoftmaxBackward0>)

In [18]:
model( torch.FloatTensor( [[5,6], [2,1] ]) ).argmax(dim=1)

tensor([1, 2])