In [1]:
import tensorflow as tf
import numpy as np

### scalar data

In [2]:
s1 = 10
s2 = 3.14
s3 = 'abc'

### vector data

In [3]:
v = [10,20,30]

### matrix data

In [ ]:
m = [ [10,20,30], [40,50,60] ] # 2x3

### 3d tensor

In [5]:
d3 =[ [ [10,20,30], [40,50,60] ],  [ [10,20,30], [40,50,60] ] ]#2x2x3

### 4d tensor

In [4]:
d4 =[ [ [ [10,20,30], [40,50,60] ],  [ [10,20,30], [40,50,60] ] ],
[ [ [10,20,30], [40,50,60] ],  [ [10,20,30], [40,50,60] ] ] ] # 2x2x2x3

### 텐서 데이터노드 정의 하는 방법
- constant : 읽기전용
- Variable: 읽기 쓰기

In [7]:
s1 = 10
c1 = tf.constant( s1 )
print( type(c1))
c1

<class 'tensorflow.python.framework.ops.EagerTensor'>


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [8]:
c1.numpy()

np.int32(10)

In [9]:
v1 = tf.constant( [10,20,30])
v1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [10]:
v1.numpy()

array([10, 20, 30], dtype=int32)

In [11]:
m1 = tf.constant([ [10,20,30], [40,50,60] ] )
m1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>

### 사칙연산: add(+), sub(-), multiply(*), div(/)
- broad casting
- element wise

In [17]:
a = tf.constant(3)
b = tf.constant( [1,2,3])
# c = tf.add(a,b)
# c = a + b 
# c = tf.multiply(a,b)
c = a*b
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9], dtype=int32)>

In [16]:
c.numpy()

array([3, 6, 9], dtype=int32)

In [18]:
d = tf.add(a,b)
d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [19]:
e = c+d
e

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7, 11, 15], dtype=int32)>

In [20]:
f = tf.constant([1,2,3])
g = tf.constant( [ [1,2,3],[4,5,6],[7,8,9] ])
h = f+g # tf.add(f,g)
h

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]], dtype=int32)>

### 행렬곱

In [2]:
o = tf.constant( [[1,2],[3,4]])
p = tf.constant( [[5,6],[7,8]])
q = tf.multiply(o,p)
r = tf.matmul( o,p)

In [3]:
q.numpy()

array([[ 5, 12],
       [21, 32]], dtype=int32)

In [4]:
r.numpy()

array([[19, 22],
       [43, 50]], dtype=int32)

### 많이 사용하는 연산

In [3]:
s =tf.constant([1,2,3] )
#t = tf.square(s) 
t = s**2
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [4]:
u = tf.reduce_mean( s )
u

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [5]:
v = tf.reduce_sum( s )
v

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [6]:
v = tf.Variable(10)
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [7]:
v.assign(20)
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>

In [8]:
v.assign_add(2)
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=22>

In [9]:
v.assign_sub(3)
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=19>