In [1]:
import tensorflow as tf
from keras.optimizers import Adam
from keras import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('data/test.csv', header=None)
df.columns = ['q1','q2', 'mid','final']
df

,q1,q2,mid,final
0,73,80,75,152
1,93,88,93,185
2,89,91,90,180
3,96,98,100,196
4,73,66,70,142
5,53,46,55,101
6,69,74,77,149
7,47,56,60,115
8,87,79,90,175
9,79,70,88,164


In [5]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [7]:
x.shape

(25, 3)

In [ ]:
# 1. hx = matmul(x, w) + b
# 2. w [3,1], b[1]
dense = Dense( units=1, input_dim=3 )
print( dense(x) ) # hx = matmul(x,w) + b
w,b = dense.get_weights()
print( w )
print( b )

tf.Tensor(
[[-53.32185 ]
 [-79.69094 ]
 [-70.358574]
 [-78.11621 ]
 [-63.424442]
 [-50.87844 ]
 [-56.305843]
 [-38.25192 ]
 [-79.91447 ]
 [-78.70578 ]
 [-57.369812]
 [-64.02273 ]
 [-71.45029 ]
 [-58.327232]
 [-59.05981 ]
 [-80.84244 ]
 [-58.586716]
 [-64.89572 ]
 [-65.47838 ]
 [-57.167515]
 [-67.73891 ]
 [-75.21103 ]
 [-62.83748 ]
 [-50.774094]
 [-79.446175]], shape=(25, 1), dtype=float32)
[[-1.0704788 ]
 [ 0.9747373 ]
 [-0.70874506]]
[0.]


c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
dense = Dense( units=1, input_dim=3)
model = Sequential( [dense]) # dense의  w와 b가 학습대상이다
model.compile( loss='mse', optimizer= Adam(0.1) )
model.fit( x, y, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 326ms/step - loss: 31353.1582
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 23331.8203
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 16536.6875
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 10975.8047
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 6636.0273
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 3475.2056
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1414.1854
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 329.9985
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 53.6319
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 376.4098
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 1067.3284
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1899.5518
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 2679.0264
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 3266.1140
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 3

In [10]:
w,b = dense.get_weights()
print( w )
print( b )

[[1.1683209 ]
 [0.47443372]
 [0.38215536]]
[0.83629304]


In [11]:
dense(x)

<tf.Tensor: shape=(25, 1), dtype=float32, numpy=
array([[152.74007],
       [186.78076],
       [182.3843 ],
       [197.70512],
       [144.18721],
       [105.59981],
       [145.9845 ],
       [105.24499],
       [174.35445],
       [159.97366],
       [142.55814],
       [141.73643],
       [189.33748],
       [158.98567],
       [147.06053],
       [188.40166],
       [153.53441],
       [173.70978],
       [180.16179],
       [160.76927],
       [171.83388],
       [174.22726],
       [163.8265 ],
       [156.1397 ],
       [193.4222 ]], dtype=float32)>

In [ ]:
model.predict( x) # 1.기본전처리. 2.dense(x) 3. 결과를  numpy로

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


array([[152.74007],
       [186.78076],
       [182.3843 ],
       [197.70512],
       [144.18721],
       [105.59981],
       [145.9845 ],
       [105.24499],
       [174.35445],
       [159.97366],
       [142.55814],
       [141.73643],
       [189.33748],
       [158.98567],
       [147.06053],
       [188.40166],
       [153.53441],
       [173.70978],
       [180.16179],
       [160.76927],
       [171.83388],
       [174.22726],
       [163.8265 ],
       [156.1397 ],
       [193.4222 ]], dtype=float32)

In [ ]:
# q1: 73, q2:80,  mid:75
model.predict( np.array([[73,80,75]]) ) 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


array([[152.74007]], dtype=float32)

part1 
electric.csv
1. 케라스,tensorflow 학습
2. scatter 와 예측선
3. 전기생산량 4, 5인경우 전기사용량 예측
4. 결정계수( sklearn이용)

part2
trees.csv
1. 케라스 학습
2. 예측값과, 실제값 plot
3. 11.1, 80 인경우 volume 예측
4. 결정계수