In [2]:
import tensorflow as tf
from keras.optimizers import Adam
from keras import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv( 'data/softmax.txt',sep=' ', header=None)
df

,0,1,2,3,4
0,2,1,0,0,1
1,3,2,0,0,1
2,3,4,0,0,1
3,5,5,0,1,0
4,7,5,0,1,0
5,2,5,0,1,0
6,6,6,1,0,0
7,7,7,1,0,0


In [4]:
x_data = df.iloc[:, :2].values
y_data = df.iloc[:, 2:].values

In [5]:
x_data.shape

(8, 2)

In [6]:
y_data.shape

(8, 3)

In [7]:
x = tf.constant( x_data, tf.float32)
y = tf.constant( y_data, tf.float32)

In [8]:
initX = tf.initializers.GlorotUniform()
w = tf.Variable( initX(shape=[2,3]))#(특성데이터갯수, 라벨의갯수)
b = tf.Variable( initX(shape=[3]) ) #(라벨의 갯수)

In [9]:
lr = 0.01
optimizer = tf.keras.optimizers.Adam( learning_rate=lr)
for i in range(2000):
    with tf.GradientTape() as tape:
        z = tf.matmul(x,w) + b
        cost_i = tf.nn.softmax_cross_entropy_with_logits(labels=y, logits=z)
        cost = tf.reduce_mean( cost_i)
    
    gradients = tape.gradient( cost, [w,b] )
    optimizer.apply_gradients(  zip( gradients,[w,b] )  )
    print( 'cost', cost.numpy())    
print('최종w', w.numpy() )
print('최종b', b.numpy() )

cost 4.9244967
cost 4.804303
cost 4.6848354
cost 4.566217
cost 4.448597
cost 4.332146
cost 4.217061
cost 4.103572
cost 3.99194
cost 3.8824635
cost 3.7754803
cost 3.6713655
cost 3.5705261
cost 3.4733903
cost 3.3803833
cost 3.2918892
cost 3.2081976
cost 3.1294308
cost 3.0554724
cost 2.9859185
cost 2.9200783
cost 2.857048
cost 2.7958393
cost 2.7355127
cost 2.6752858
cost 2.6145844
cost 2.5530488
cost 2.4905102
cost 2.4269533
cost 2.362475
cost 2.2972527
cost 2.2315097
cost 2.1654973
cost 2.0994766
cost 2.033705
cost 1.9684318
cost 1.9038926
cost 1.8403093
cost 1.777892
cost 1.7168444
cost 1.6573672
cost 1.5996664
cost 1.5439581
cost 1.4904752
cost 1.4394711
cost 1.3912199
cost 1.3460135
cost 1.3041549
cost 1.2659421
cost 1.2316518
cost 1.2015122
cost 1.1756779
cost 1.1542029
cost 1.1370187
cost 1.1239246
cost 1.1145875
cost 1.1085597
cost 1.1053045
cost 1.1042354
cost 1.1047525
cost 1.1062808
cost 1.1082989
cost 1.1103611
cost 1.1121101
cost 1.1132808
cost 1.1136975
cost 1.1132677
cost 1.

In [10]:
w.shape

TensorShape([2, 3])

In [11]:
def hxFn( xd):
   xd = tf.constant( xd, tf.float32)
   z = tf.matmul(xd,w) + b 
   hx = tf.nn.softmax(z)
   return hx.numpy(), np.argmax( hx.numpy(), axis=1)

In [12]:
hxFn( [[5,6]] )[1]

array([0])

In [13]:
# 토론후
# iris 데이터셋 학습 1,2 행의 분류

In [23]:
from sklearn.datasets import load_iris
from keras.utils import to_categorical

iris = load_iris()
x_data = pd.DataFrame(iris.data, columns=iris.feature_names)
y_data=to_categorical(iris.target)


In [24]:
x = tf.constant( x_data, tf.float32)
y = tf.constant( y_data, tf.float32)

In [28]:
initX = tf.initializers.GlorotUniform()
w = tf.Variable( initX(shape=[4,3]))#(특성데이터갯수, 라벨의갯수)
b = tf.Variable( initX(shape=[3]) ) #(라벨의 갯수)

In [29]:
lr = 0.01
optimizer = tf.keras.optimizers.Adam( learning_rate=lr)
for i in range(2000):
    with tf.GradientTape() as tape:
        z = tf.matmul(x,w) + b
        cost_i = tf.nn.softmax_cross_entropy_with_logits(labels=y, logits=z)
        cost = tf.reduce_mean( cost_i)
    
    gradients = tape.gradient( cost, [w,b] )
    optimizer.apply_gradients(  zip( gradients,[w,b] )  )
    print( 'cost', cost.numpy())    
print('최종w', w.numpy() )
print('최종b', b.numpy() )

cost 3.33798
cost 3.1948142
cost 3.059503
cost 2.931628
cost 2.809462
cost 2.6911774
cost 2.576036
cost 2.4637635
cost 2.3541498
cost 2.2470036
cost 2.1422205
cost 2.039873
cost 1.9402906
cost 1.8441085
cost 1.7522767
cost 1.6660427
cost 1.5868903
cost 1.5164264
cost 1.4561918
cost 1.407393
cost 1.3705918
cost 1.3454334
cost 1.3305421
cost 1.3236661
cost 1.3220397
cost 1.3228382
cost 1.3235672
cost 1.3223106
cost 1.3178242
cost 1.3095142
cost 1.2973472
cost 1.2817278
cost 1.2633662
cost 1.2431526
cost 1.2220392
cost 1.2009342
cost 1.1806121
cost 1.1616453
cost 1.1443646
cost 1.1288542
cost 1.1149846
cost 1.1024728
cost 1.090963
cost 1.0801007
cost 1.0695935
cost 1.059244
cost 1.0489552
cost 1.0387132
cost 1.0285579
cost 1.0185509
cost 1.0087475
cost 0.99917907
cost 0.9898461
cost 0.98072207
cost 0.9717616
cost 0.96291596
cost 0.95414174
cost 0.945412
cost 0.9367198
cost 0.9280774
cost 0.9195146
cost 0.91107035
cost 0.9027893
cost 0.8947118
cost 0.8868712
cost 0.879288
cost 0.8719685
co

In [30]:
def hxFn( xd):
   xd = tf.constant( xd, tf.float32)
   z = tf.matmul(xd,w) + b 
   hx = tf.nn.softmax(z)
   return hx.numpy(), np.argmax( hx.numpy(), axis=1)

In [34]:
hxFn( x_data.head(5) )

(array([[9.9479252e-01, 5.2074832e-03, 1.4452033e-10],
        [9.7218531e-01, 2.7814725e-02, 2.9687091e-09],
        [9.9021739e-01, 9.7826011e-03, 7.3561113e-10],
        [9.7931802e-01, 2.0681944e-02, 3.8215844e-09],
        [9.9656630e-01, 3.4336804e-03, 9.1368711e-11]], dtype=float32),
 array([0, 0, 0, 0, 0]))

In [35]:
dense=Dense(units=3,input_dim=4,activation='softmax')

c:\Users\Dell5371\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
