In [1]:
import tensorflow as tf
from keras.optimizers import Adam
from keras import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv( 'data/softmax.txt',sep=' ', header=None)
df

,0,1,2,3,4
0,2,1,0,0,1
1,3,2,0,0,1
2,3,4,0,0,1
3,5,5,0,1,0
4,7,5,0,1,0
5,2,5,0,1,0
6,6,6,1,0,0
7,7,7,1,0,0


In [15]:
x_data = df.iloc[:, :2].values.astype(np.float32)
y_data = df.iloc[:, 2:].values

In [16]:
x_data.shape

(8, 2)

In [7]:
y_data.shape

(8, 3)

In [18]:
# z = matmul(x,w) +b 
# hx = softmax( z )
dense = Dense(units=3, input_dim=2, activation='softmax')# w:2x3[특정데이터,라벨], b:3 [라벨의갯수]
dense(x_data)

c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[3.7538832e-01, 5.8528793e-01, 3.9323758e-02],
       [2.5354579e-01, 7.3441768e-01, 1.2036599e-02],
       [6.5035015e-02, 9.2309815e-01, 1.1866918e-02],
       [4.3197446e-02, 9.5597684e-01, 8.2570082e-04],
       [6.0283318e-02, 9.3965518e-01, 6.1569393e-05],
       [2.5008792e-02, 9.3628740e-01, 3.8703788e-02],
       [2.3740325e-02, 9.7605407e-01, 2.0564806e-04],
       [1.2922419e-02, 9.8702687e-01, 5.0728813e-05]], dtype=float32)>

In [19]:
w, b = dense.get_weights()
print(w)
print('------')
print(b)

[[ 0.830129   0.6548815 -0.6345422]
 [ 0.2689501  1.0635881  0.9421606]]
------
[0. 0. 0.]


In [23]:
x_data.shape

(8, 2)

In [27]:
z = tf.matmul(x_data, w) +b
hx = tf.nn.softmax(z)
hx.numpy().argmax(axis=1)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
dense = Dense(units=3, input_dim=2, activation='softmax')
model = Sequential([dense])
model.compile( loss='categorical_crossentropy', optimizer=Adam(0.1) , metrics=['acc'])
h = model.fit( x_data, y_data, epochs=500)

Epoch 1/500


c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 389ms/step - acc: 0.5000 - loss: 1.6636
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5000 - loss: 1.1299
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.3750 - loss: 1.1492
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.2500 - loss: 1.2688
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.3750 - loss: 1.1284
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.6250 - loss: 0.9877
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5000 - loss: 0.9965
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.5000 - loss: 1.0559
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5000 - loss: 1.0628
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5000 - loss: 1.0094
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5000 - loss: 0.9341
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.5000 - loss: 0.8921
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.

In [29]:
w, b = dense.get_weights()
print(w)
print('------')
print(b)

[[ 0.11884087  0.0190857  -0.22440644]
 [ 1.5181458  -1.2581215  -4.2925115 ]]
------
[-13.059654    3.2337244  17.058071 ]


In [32]:
dense( x_data).numpy().argmax(axis=1)

array([2, 2, 2, 1, 1, 1, 0, 0])

In [34]:
y_data.argmax(axis=1)

array([2, 2, 2, 1, 1, 1, 0, 0])

In [36]:
model.predict( x_data ).argmax(axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


array([2, 2, 2, 1, 1, 1, 0, 0])

In [ ]:
## iris 데이터셋 케라스로 학습하고
## 1,2행의 예측값을 구하시요.

In [38]:
from sklearn.datasets import load_iris
from keras.utils import to_categorical

In [39]:
iris = load_iris( as_frame=True)
iris['frame']

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [40]:
x_data = iris['data'].values
y_data = to_categorical( iris['target'] )

In [41]:
dense = Dense(units=3, input_dim=4, activation='softmax')
model = Sequential([dense])
model.compile( loss='categorical_crossentropy', optimizer=Adam(0.1) , metrics=['acc'])
h = model.fit( x_data, y_data, epochs=500)

Epoch 1/500


c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.3200 - loss: 1.8717  
Epoch 2/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.6600 - loss: 1.0303 
Epoch 3/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.6267 - loss: 0.7091 
Epoch 4/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.7333 - loss: 0.4988 
Epoch 5/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.7867 - loss: 0.4655 
Epoch 6/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.7400 - loss: 0.4212 
Epoch 7/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8933 - loss: 0.3695 
Epoch 8/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.7667 - loss: 0.3974 
Epoch 9/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8667 - loss: 0.3546 
Epoch 10/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9000 - loss: 0.3249 
Epoch 11/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8800 - loss: 0.3100 
Epoch 12/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9400 - loss: 0.2743 
Epoch 13/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9

In [45]:
model.predict( x_data[[0,1]] ).argmax(axis=1) # 2x4 4x3 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([0, 0])