In [15]:
import tensorflow as tf
from keras.optimizers import Adam
from keras import Sequential
from keras.layers import Dense, Input
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
x = np.array( [[0,0],[0,1],[1,0],[1,1]] )
y = np.array( [[0],[1],[1],[0]] )

# w1 = tf.Variable( initX(shape=[2,100]))
# b1 = tf.Variable( initX(shape=[100]) ) 
# w2 = tf.Variable( initX(shape=[100,1]))
# b2 = tf.Variable( initX(shape=[1]) ) 

In [6]:
dense1 = Dense( units=100, input_dim=2, activation='sigmoid')# w:2x100 b:100
dense2 = Dense( units=1, input_dim=100, activation='sigmoid')# w:100x1 : 1
model = Sequential( [dense1, dense2])
model.compile( loss='binary_crossentropy', optimizer=Adam(0.1), metrics=['acc'] )
h = model.fit( x,y, epochs=500 )

Epoch 1/500


c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 540ms/step - acc: 0.5000 - loss: 0.7590
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.5000 - loss: 2.4432
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 1.2209
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.8799
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5000 - loss: 1.3814
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5000 - loss: 1.2281
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.5000 - loss: 0.8234
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.5000 - loss: 0.7067
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.5000 - loss: 0.9033
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.5000 - loss: 1.0041
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.9263
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.7736
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.

In [10]:
# 4x2 2x100 = 4x100
hx1 = dense1( x ) # z1 = matmul(x, w1) +b1  hx1 = sigmoid(z1)
# 4x100 100x1 = 4x1
hx = dense2( hx1) # z = matmul(hx1, w2) + b2 hx = sigmoid(z) 
hx

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[2.5001221e-04],
       [9.9942863e-01],
       [9.9946582e-01],
       [1.3597507e-03]], dtype=float32)>

In [8]:
model.predict( x ) 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


array([[2.5001247e-04],
       [9.9942863e-01],
       [9.9946582e-01],
       [1.3597504e-03]], dtype=float32)

In [7]:
(model.predict( x ) > 0.5) +0

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[0],
       [1],
       [1],
       [0]])

w1 = tf.Variable( initX(shape=[2,32]))
b1 = tf.Variable( initX(shape=[32]) ) 
w2 = tf.Variable( initX(shape=[32,16]))
b2 = tf.Variable( initX(shape=[16]) ) 
w3 = tf.Variable( initX(shape=[16,1]))
b3 = tf.Variable( initX(shape=[1]) ) 

In [ ]:
dense1 = Dense( units=32, input_dim=2, activation='sigmoid')# w:2x32 b:32
dense2 = Dense( units=16, input_dim=32, activation='sigmoid')# w:32x16 b: 16
dense3 = Dense( units=1, input_dim=16, activation='sigmoid')# w:16x1 b: 1
model = Sequential( [dense1, dense2, dense3] )
model.compile( loss='binary_crossentropy', optimizer=Adam(0.1), metrics=['acc'] )
h = model.fit( x,y, epochs=100 )

Epoch 1/100


c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 665ms/step - acc: 0.5000 - loss: 0.6945
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.5000 - loss: 1.4507
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.8151
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.5000 - loss: 0.9091
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - acc: 0.5000 - loss: 0.9453
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.5000 - loss: 0.7999
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.5000 - loss: 0.7075
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5000 - loss: 0.6935
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5000 - loss: 0.7076
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5000 - loss: 0.7204
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - acc: 0.5000 - loss: 0.7243
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.5000 - loss: 0.7206
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.

In [ ]:
hx1 = dense1(x) # 4x2 2x32 = 4x32
hx2 = dense2(hx1)# 4x32 32x16 = 4x16
hx = dense3(hx2) # 4x16 16x1 = 4x1
hx

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.01268092],
       [0.99004465],
       [0.98949575],
       [0.01572057]], dtype=float32)>

In [12]:
model.predict(x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


array([[0.01268092],
       [0.99004465],
       [0.98949575],
       [0.01572057]], dtype=float32)

In [13]:
(model.predict(x) >0.5) +0

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


array([[0],
       [1],
       [1],
       [0]])

## hidden layer층: relu

In [17]:
myin  = Input(shape=(2,) ) # 입력층: input layer
dense1 = Dense( units=32, activation='relu')# w:2x32 b:32   #hidden layer
dense2 = Dense( units=16, activation='relu')# w:32x16 b: 16  #hidden layer
dense3 = Dense( units=1,  activation='sigmoid')# w:16x1 b: 1  # output layer
model = Sequential( [myin, dense1, dense2, dense3] )
model.compile( loss='binary_crossentropy', optimizer=Adam(0.1), metrics=['acc'] )
h = model.fit( x,y, epochs=100 )

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 670ms/step - acc: 0.5000 - loss: 0.7137
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.5000 - loss: 0.6909
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7500 - loss: 0.6524
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.6081
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 1.0000 - loss: 0.5236
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7500 - loss: 0.4515
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.3279
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.2217
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.1332
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.0723
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.0349
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.0160
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/st

### 퀴즈 : iris 데이터 딥러닝으로  구성해서 train, test 의 정확도 확인

In [41]:
from sklearn.datasets import load_iris
from keras.utils import to_categorical
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [42]:
iris = load_iris()

In [43]:
x = iris['data']
y = to_categorical( iris['target'] )

In [44]:
x_train, x_test, y_train,y_test = train_test_split(x,y, test_size=0.2,stratify=y)

In [45]:
myin  = Input(shape=(4,) ) 
dense1 = Dense( units=32, activation='relu')
dense2 = Dense( units=16, activation='relu')
dense3 = Dense( units=3,  activation='softmax')
model = Sequential( [myin, dense1, dense2, dense3] )
model.compile( loss='categorical_crossentropy', optimizer=Adam(0.01), 
              metrics=['acc'] )
h = model.fit( x_train,y_train, epochs=500 )

Epoch 1/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.3083 - loss: 1.5142  
Epoch 2/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.6250 - loss: 0.7874 
Epoch 3/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.8333 - loss: 0.6113 
Epoch 4/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.7333 - loss: 0.5199 
Epoch 5/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9417 - loss: 0.4103 
Epoch 6/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9333 - loss: 0.3567 
Epoch 7/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9333 - loss: 0.3008 
Epoch 8/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9583 - loss: 0.2573 
Epoch 9/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9667 - loss: 0.2220 
Epoch 10/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9667 - loss: 0.1992 
Epoch 11/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9583 - loss: 0.1782 
Epoch 12/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9750 - loss: 0.1656 
Epoch 13/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/ste

In [49]:
pred = model.predict( x_train ).argmax(axis=1)
accuracy_score( y_train.argmax(axis=1), pred )

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 


0.9833333333333333

In [50]:
pred = model.predict( x_test ).argmax(axis=1)
accuracy_score( y_test.argmax(axis=1), pred )

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


0.9333333333333333